name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Debug output
        env:
          BUILD_CONTEXT: ${{ github.workspace }}
        run: |
          set -v
          echo $BUILD_CONTEXT
          ls -lha $BUILD_CONTEXT
          echo $PWD
          ls -lha
      - uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          tags: |
            lpeabody/drupal-security:latest